# Generated by Django 5.2.1 on 2025-06-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ciutat', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equips_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Torneig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('data_inici', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tornejos_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Videojoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='videojocs_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('equip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competicions.equip')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('puntuacio_equip1', models.IntegerField()),
                ('puntuacio_equip2', models.IntegerField()),
                ('equip1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partides_com_equip1', to='competicions.equip')),
                ('equip2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partides_com_equip2', to='competicions.equip')),
                ('torneig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partides', to='competicions.torneig')),
            ],
        ),
        migrations.AddField(
            model_name='torneig',
            name='videojoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicions.videojoc'),
        ),
        migrations.AddField(
            model_name='equip',
            name='videojoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicions.videojoc'),
        ),
    ]
