# Generated by Django 5.2.1 on 2025-06-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ronda',
            field=models.CharField(choices=[('OCTAUS', 'Octaus de final'), ('QUARTS', 'Quarts de final'), ('SEMIS', 'Semifinals'), ('FINAL', 'Final')], default='OCTAUS', max_length=10),
        ),
    ]
