# Generated by Django 5.2.1 on 2025-06-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions', '0002_partida_ronda'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneig',
            name='equips',
            field=models.ManyToManyField(related_name='tornejos', to='competicions.equip'),
        ),
    ]
